[package]
name = "pasta_trabalho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libxlsxwriter-sys = "1.1.5"
xlsxwriter = "0.6.0"
